export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const CLEAR_ENTRIES = 'CLEAR_ENTRIES';
export const SWITCH_SPORT = 'SWITCH_SPORT';
export const SWITCH_DRAFTGROUP = 'SWITCH_DRAFTGROUP';
export const SWITCH_CONTEST_TYPE = 'SWITCH_CONTEST_TYPE';
export const SWITCH_ACCESS_TYPE = 'SWITCH_ACCESS_TYPE';
