export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const CLEAR_ENTRIES = 'CLEAR_ENTRIES';
export const SWITCH_SPORT = 'SWITCH_SPORT';
export const SWITCH_DRAFTGROUP = 'SWITCH_DRAFTGROUP';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
